import { NextResponse } from 'next/server';
import { Priority, Prisma } from '@prisma/client';
import { z } from 'zod';
import { requireSession } from '@/lib/auth';
import { db } from '@/lib/db';
import { apiError } from '@/lib/http';
import { dueAt } from '@/lib/sla';
import { scoreFusion } from '@/lib/fusion';
const createInput=z.object({category:z.string().min(2).max(50),description:z.string().min(10).max(2000),building:z.string().min(1).max(60),floor:z.string().max(20).optional(),unit:z.string().max(30).optional(),assetId:z.string().optional(),priority:z.nativeEnum(Priority).optional()});
export async function GET(request:Request){try{const user=await requireSession();const {searchParams}=new URL(request.url);const page=Math.max(1,Number(searchParams.get('page')||1));const limit=Math.min(50,Math.max(1,Number(searchParams.get('limit')||20)));const where:Prisma.ComplaintWhereInput={societyId:user.societyId,...(user.role==='RESIDENT'?{reporterId:user.id}:{})};for(const field of ['status','category'] as const){const value=searchParams.get(field);if(value) Object.assign(where,{[field]:value});}const [items,total]=await Promise.all([db.complaint.findMany({where,include:{asset:true,reporter:{select:{name:true,email:true}},histories:{orderBy:{createdAt:'desc'},take:1}},orderBy:{createdAt:'desc'},skip:(page-1)*limit,take:limit}),db.complaint.count({where})]);return NextResponse.json({items,total,page,limit});}catch(error){return apiError(error)}}
export async function POST(request:Request){try{const user=await requireSession();const body=createInput.parse(await request.json());if(body.assetId){const asset=await db.asset.findFirst({where:{id:body.assetId,societyId:user.societyId}});if(!asset)throw new Error('NOT_FOUND');}const openedAt=new Date();const number=await db.complaint.count({where:{societyId:user.societyId}})+1;const candidates=await db.complaint.findMany({where:{societyId:user.societyId,status:{not:'RESOLVED'},openedAt:{gt:new Date(openedAt.getTime()-48*3600000)}},take:25,orderBy:{openedAt:'desc'}});const complaint=await db.$transaction(async tx=>{const created=await tx.complaint.create({data:{displayId:`CMP-${openedAt.getUTCFullYear()}-${String(number).padStart(5,'0')}`,societyId:user.societyId,reporterId:user.id,assetId:body.assetId,category:body.category,description:body.description,building:body.building,floor:body.floor,unit:body.unit,priority:body.priority??'MEDIUM',openedAt,dueAt:dueAt(openedAt,body.priority??'MEDIUM')}});await tx.complaintHistory.create({data:{complaintId:created.id,actorId:user.id,eventType:'CREATED',newStatus:'OPEN',note:'Complaint submitted by resident.'}});return created;});const suggestion=candidates.map(candidate=>({complaintId:candidate.id,displayId:candidate.displayId,...scoreFusion({category:body.category,building:body.building,assetId:body.assetId,description:body.description,openedAt},{category:candidate.category,building:candidate.building,assetId:candidate.assetId,description:candidate.description,openedAt:candidate.openedAt})})).filter(match=>match.confidence>=45).sort((a,b)=>b.confidence-a.confidence)[0];return NextResponse.json({complaint,suggestion},{status:201});}catch(error){return apiError(error)}}
