'use client';

import { useState } from 'react';
import { ChevronRight, ClipboardPlus, Sparkles } from 'lucide-react';

export default function PersistentIntake({close,done,assetId}:{close:()=>void;done:(message:string)=>void;assetId?:string}) {
  const [step,setStep]=useState(1); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  const [form,setForm]=useState({category:'Elevator',description:'',building:'Tower B',floor:'',unit:''});
  const [photo,setPhoto]=useState<File|null>(null);
  const save=async()=>{setSaving(true);setError('');const response=await fetch('/api/complaints',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,assetId})});if(!response.ok){setError('Unable to submit your complaint. Please check the details and try again.');setSaving(false);return;}const result=await response.json();const complaint=result.complaint;if(photo){const upload=new FormData();upload.set('complaintId',complaint.id);upload.set('file',photo);const uploadResponse=await fetch('/api/uploads',{method:'POST',body:upload});if(!uploadResponse.ok){done(`${complaint.displayId} created, but the photo could not be uploaded.`);close();return;}}done(`${complaint.displayId} created${result.suggestion?` — possible related report: ${result.suggestion.displayId} (${result.suggestion.confidence}% match)`:''}.`);close();};
  return <main className="intake"><header className="intake-header"><div className="brand"><span className="brand-mark">N</span><span>Nivasa <b>Pulse</b><small>SKYLINE HEIGHTS</small></span></div><button className="secondary" onClick={close}>Save & exit</button></header><div className="intake-body"><span className="eyebrow">RAISE A COMPLAINT</span><h1>Let’s get this sorted.</h1><p>Clear details help the right team act faster.</p><div className="steps"><span className={step>=1?'current':''}>1 <b>What happened?</b></span><i/><span className={step>=2?'current':''}>2 <b>Review</b></span><i/><span className={step>=3?'current':''}>3 <b>Confirm</b></span></div>{step===1&&<div className="form-card"><label>What needs attention?<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Elevator</option><option>Plumbing</option><option>Electrical</option><option>Security</option><option>General</option></select></label><label>Describe the issue<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Describe what happened, where it is happening, and how it affects you."/></label><div className="form-grid"><label>Building / wing<select value={form.building} onChange={e=>setForm({...form,building:e.target.value})}><option>Tower A</option><option>Tower B</option><option>Tower C</option></select></label><label>Floor<input value={form.floor} onChange={e=>setForm({...form,floor:e.target.value})} placeholder="e.g. 4"/></label></div><label>Apartment / unit (optional)<input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})} placeholder="e.g. B-402"/></label><label>Photo (optional)<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhoto(e.target.files?.[0]||null)}/><small>{photo?photo.name:'JPEG, PNG or WebP · Maximum 5 MB'}</small></label><button className="primary wide" disabled={form.description.trim().length<10} onClick={()=>setStep(2)}>Continue <ChevronRight size={17}/></button></div>}{step===2&&<div className="analysis-card"><div className="analysis-title"><span><Sparkles size={20}/></span><div><b>Review your report</b><small>The operations team will assess urgency and possible related incidents.</small></div></div><div className="duplicate"><div><b>{form.category} · {form.building}{form.floor?` · Floor ${form.floor}`:''}</b><p>{form.description}</p></div></div><button className="primary wide" onClick={()=>setStep(3)}>Continue <ChevronRight size={17}/></button></div>}{step===3&&<div className="form-card review"><span className="section-label">READY TO SEND</span><h2>{form.category} issue</h2><p>{form.description}</p>{photo&&<p>Photo: {photo.name}</p>}{error&&<p className="red">{error}</p>}<button className="primary wide" disabled={saving} onClick={save}><ClipboardPlus size={17}/>{saving?'Submitting…':'Submit complaint'}</button></div>}</div></main>;
}
